# Numerical python

In [1]:
import numpy as np

In [2]:
x=np.random.random(1000000)

In [3]:
x

array([0.21348407, 0.66601982, 0.29342538, ..., 0.98197807, 0.75320612,
       0.70946851])

In [4]:
x.shape

(1000000,)

In [5]:
import time

In [7]:
start=time.time()
sum(x)/len(x)
print(time.time()-start)

1.618990182876587


In [8]:
start=time.time()
np.mean(x)
print(time.time()-start)

0.004541873931884766


In [10]:
z=np.array([[1,2,3,4,5]])

In [11]:
z.shape

(1, 5)

In [12]:
y=np.array(([1],[2],[3],[4],[5]))

In [13]:
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
z

array([[1, 2, 3, 4, 5]])

In [15]:
z.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
y.T

array([[1, 2, 3, 4, 5]])

In [21]:
m=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
m


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
m.shape

(3, 3)

In [24]:
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
m.size

9

In [26]:
np.save("3x3Array",m)

In [27]:
p=np.load("3x3Array.npy")

In [28]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.full((4,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.linspace(0,25,10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [37]:
z

array([[1, 2, 3, 4, 5]])

In [38]:
np.reshape(z,(2,2))

ValueError: cannot reshape array of size 5 into shape (2,2)

In [39]:
v=np.array([1,2,3,4])

In [40]:
v

array([1, 2, 3, 4])

In [42]:
b=np.reshape(v,(2,2))

In [43]:
b

array([[1, 2],
       [3, 4]])

In [45]:
b

array([[1, 2],
       [3, 4]])

In [46]:
b*2

array([[2, 4],
       [6, 8]])