# Numpy :Scintific Computing 

In [1]:
import numpy as np

In [2]:
x=np.random.random(10000000)

In [3]:
x

array([0.63738617, 0.07496666, 0.41028762, ..., 0.12711984, 0.20976822,
       0.17019645])

In [4]:
x.shape

(10000000,)

In [5]:
type(x)

numpy.ndarray

In [6]:
import time
start=time.time()
sum(x)/len(x)
print(time.time()-start)

1.064507007598877


In [7]:
start=time.time()
np.mean(x)
print(time.time()-start)

0.011237859725952148


In [8]:
v=np.array([[1,2,3,4]])

In [9]:
v

array([[1, 2, 3, 4]])

In [10]:
v.shape

(1, 4)

In [ ]:
v2=

In [11]:
arr=np.array([2,4,6,8])

In [12]:
arr

array([2, 4, 6, 8])

In [13]:
arr.shape

(4,)

In [14]:
z=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
z.shape

(3, 3)

In [17]:
z.size

9

In [18]:
np.save('An_array',z)

In [19]:
y=np.load('An_array.npy')

In [20]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.diag([10,5,6,7,8])

array([[10,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  7,  0],
       [ 0,  0,  0,  0,  8]])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.linspace(0,25,10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [ ]:
listages=[1,2,3,4,5]

# Vectors

In [5]:
import numpy as np
c=np.array(([5],[6],[7]))

In [7]:
c

array([[5],
       [6],
       [7]])

In [6]:
c.shape

(3, 1)

In [11]:
m=np.array([[1,2,3]])

In [12]:
m

array([[1, 2, 3]])

In [13]:
m.shape

(1, 3)

In [14]:
c

array([[5],
       [6],
       [7]])

In [15]:
c.T

array([[5, 6, 7]])

In [17]:
m.T

array([[1],
       [2],
       [3]])

In [24]:
ma=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
ma.shape

(3, 3)

In [27]:
ma.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
p=np.reshape(ma,(1,9))

In [29]:
p

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
p.shape

(1, 9)

In [35]:
np.reshape(p,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
mb=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [7,8,9]
])

In [37]:
mb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [38]:
mb.shape

(4, 3)

In [40]:
np.reshape(mb,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 8, 9]])

In [42]:
b=mb.copy()

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [44]:
b*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81],
       [49, 64, 81]])

In [48]:
np.dot(b,b)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [50]:
k=np.dot(b,b.T)

In [51]:
k

array([[ 14,  32,  50,  50],
       [ 32,  77, 122, 122],
       [ 50, 122, 194, 194],
       [ 50, 122, 194, 194]])

In [55]:
k[1:3,1:3]

array([[ 77, 122],
       [122, 194]])

In [70]:
#row
k[:,0]

array([14, 32, 50, 50])

In [77]:
k[:,1]

array([ 32,  77, 122, 122])